### ISSUE TITLE
Colors are currently listed as yaml comments

### ISSUE THREAD

**Issue by belak** [elnawe/base16-zenburn-scheme#2]
They should be in the format `base00: "3f3f3f"`, so the # needs to be removed and the strings may need to be quoted.

**Comment by nawetimebomb** [comment]
I created this PR: https://github.com/elnawe/base16-zenburn-scheme/pull/3

Can you please take a look?

**Comment by nawetimebomb** [comment]
Fixed! Thanks for the report. I just copied another one I saw out there and didn't notice the error.
